# Generated by Django 5.0.2 on 2024-04-17 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('ac_id', models.AutoField(primary_key=True, serialize=False)),
                ('ac_name', models.CharField(max_length=50)),
                ('ac_desc', models.CharField(max_length=200)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=9)),
                ('a_date', models.DateField()),
                ('a_cat', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='budgetplan.category')),
            ],
        ),
    ]
